### PR TITLE
Initialize project

### PR DESCRIPTION
**Pull request by robertodauria**
This PR imports some initial code for the switch-monitoring daemon.

The only switch where NETCONF is enabled already is s1.lga0t.

Implemented:
- Retrieving the switches list from siteinfo (the project can be specified with `-project`)
- Getting the configuration, cleaning it from comments/blank lines, replacing the actual encrypted password with `dummy` and generating a SHA256 hash

Not implemented yet:
- Retrieving the expected configuration for a switch from GCS
- Comparing expected vs actual hashes
- Actually looping over the switches list

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/switch-monitoring/1)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
No tests? :)

> *[Reviewable](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-:-M2jR3h88bbOcdRWz--n:b-u6jdm1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade, @robertodauria, and @stephen-soltesz)

___
*[.gitignore, line 17 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jKzcg3WtXYt2c2tLw:-M2jKzch1UvGQIhKH7Rs:bsi2bqf) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/.gitignore#L17)):*
> ```ignore
> # vendor/
> 
> .vscode/
> ```

nit: weird eol spaces?
___
*[go.mod, line 1 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jL3x2D7BdmVmRtJ83:-M2jL3x3AzkwOkS70sku:bkwgize) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/go.mod#L1)):*
> ```XML
> module github.com/m-lab/switch-monitoring
> ```

Do we need go mod for this repo ? (no wrong answer, but could eliminate go.sum)
___
*[cmd/switch-monitoring/main.go, line 13 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jLJm7AkaiI8h9dFN2:-M2jLJm7AkaiI8h9dFN3:bc3r2v3) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/cmd/switch-monitoring/main.go#L13)):*
> ```Go
> 	"github.com/m-lab/go/flagx"
> 	"github.com/m-lab/go/rtx"
> 	"github.com/m-lab/switch-monitoring/cmd/switch-monitoring/client"
> ```

The location of these support packages seem out of the ordinary. I would expect to find them at the top level directory. Maybe in an `internal/` toplevel subdirectory. Why subdirectories of cmd ?
___
*[cmd/switch-monitoring/main.go, line 35 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jLkUW6qyUSxhXaH1n:-M2jLkUW6qyUSxhXaH1o:b8bber) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/cmd/switch-monitoring/main.go#L35)):*
> ```Go
> 	log.SetHandler(text.New(os.Stdout))
> 
> 	flag.Parse()
> ```

flagDebug is referenced above before flags are parsed here.
___
*[cmd/switch-monitoring/main.go, line 45 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jNGAR7w_iRnyh0hoL:-M2jNGAR7w_iRnyh0hoM:bpsoqfp) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/cmd/switch-monitoring/main.go#L45)):*
> ```Go
> 
> 	// Initialize Siteinfo provider and the NETCONF client.
> 	siteinfo := &siteinfo.Siteinfo{ProjectID: *flagProject}
> ```

That's a lot of "siteinfo". I suggest calling the struct `siteinfo.Client{}`. And, please use a different variable and package name.
___
*[cmd/switch-monitoring/switch-monitoring, line 0 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jO9UzCje-Y9tdbNOV:-M2jO9UzCje-Y9tdbNOW:b-rh93ak) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/cmd/switch-monitoring/switch-monitoring#L0)):*
This looks like a mistake? Please remove.
___
*[cmd/switch-monitoring/client/netconf.go, line 1 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jNizm3H7CnOuCLkX6:-M2jNizm3H7CnOuCLkX7:b-puqn6q) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/cmd/switch-monitoring/client/netconf.go#L1)):*
> ```Go
> package client
> ```

I suggest naming this package `netconf`. Then, usage would look like `netconf.Client` or `netconf.New`.
___
*[cmd/switch-monitoring/client/netconf.go, line 54 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jPkYn4z7Nb1gAAMl2:-M2jPkYn4z7Nb1gAAMl3:b-9k1u0a) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/cmd/switch-monitoring/client/netconf.go#L54)):*
> ```Go
> 	// Replace all password fields with "dummy".
> 	re = regexp.MustCompile("encrypted-password.+")
> 	config = re.ReplaceAllString(config, "encrypted-password \"dummy\";")
> ```

Can we identify the default password hash? (eventually?)
___
*[cmd/switch-monitoring/siteinfo/siteinfo.go, line 1 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jM1nH9M2tAhIRxeFe:-M2jM1nH9M2tAhIRxeFf:bk54h2d) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/cmd/switch-monitoring/siteinfo/siteinfo.go#L1)):*
> ```Go
> package siteinfo
> ```

This package makes me happy. Please consider making it part of m-lab/go. It's not impossible for jsonnet to generate Go structs for the output formats supported by m-lab/siteinfo.
___
*[cmd/switch-monitoring/siteinfo/siteinfo.go, line 32 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jMVNy2EFy2xHE0lRi:-M2jMVNy2EFy2xHE0lRj:bbmzmsp) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/cmd/switch-monitoring/siteinfo/siteinfo.go#L32)):*
> ```Go
> }
> 
> func (s Siteinfo) Sites() ([]string, error) {
> ```

If you want to generalize this package for m-lab/go/siteinfo, I suggest naming the functions after the output format.
___
*[cmd/switch-monitoring/siteinfo/siteinfo.go, line 62 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jQ5gSBFRSbGfvpg-g:-M2jQ5gSBFRSbGfvpg-h:boe1qz2) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/cmd/switch-monitoring/siteinfo/siteinfo.go#L62)):*
> ```Go
> 	url := fmt.Sprintf(baseURLFormat+"sites/switches.json", s.ProjectID)
> 
> 	resp, err := http.Get(url)
> ```

If this package will be part of a long-lived daemon, then I suggest using http requests with timeouts. This could be by using a custom `http.DefaultClient` (no timeouts) or using `http.NewRequestWithContext` with a context timeout.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/switch-monitoring/1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @robertodauria)

___
*[netconf/client.go, line 44 at r2](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2niQ6V20uHRpa0HCdJ:-M2niQ6V20uHRpa0HCdK:bb11bbt) ([raw file](https://github.com/m-lab/switch-monitoring/blob/aeb0780b177275422d0679411395da91cb9aca98/netconf/client.go#L44)):*
> ```Go
> 
> 	// Remove comments (lines starting with '#') and trim the result.
> 	re := regexp.MustCompile("(?m)^#.*$")
> ```

Is this only intended to remove the first comment line in the file, inserted dynamically by JunOS?

**Review by robertodauria — COMMENTED** [review]
@stephen-soltesz PTAL again?

> *[Reviewable](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-:-M3BjwAI8c1RSMFawiBS:b-hb6imj)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[go.mod, line 1 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jL3x2D7BdmVmRtJ83:-M3BhMRh4cSaM9trDTtM:b-p820cv) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/go.mod#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Do we need go mod for this repo ? (no wrong answer, but could eliminate go.sum)
</blockquote></details>

Done. Discussed on Slack, now it's apparently the recommended way to organize a new Go project (https://golang.org/doc/code.html#Organization)
___
*[cmd/switch-monitoring/main.go, line 13 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jLJm7AkaiI8h9dFN2:-M3BhePc6o_Qvq1_6k7l:bp8kkzy) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/cmd/switch-monitoring/main.go#L13)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The location of these support packages seem out of the ordinary. I would expect to find them at the top level directory. Maybe in an `internal/` toplevel subdirectory. Why subdirectories of cmd ?
</blockquote></details>

Done. I've moved them to an `/internal` folder. `siteinfo` could be moved to m-lab/go in future.
___
*[cmd/switch-monitoring/main.go, line 35 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jLkUW6qyUSxhXaH1n:-M3BhpyN2gvDsLz1PJqQ:b-ub6rs8) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/cmd/switch-monitoring/main.go#L35)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

flagDebug is referenced above before flags are parsed here.
</blockquote></details>

Done. That's embarassing. :face_with_head_bandage: 
___
*[cmd/switch-monitoring/main.go, line 45 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jNGAR7w_iRnyh0hoL:-M3Bi8Hx3x0nAntd8ipx:b-9kjeu9) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/cmd/switch-monitoring/main.go#L45)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

That's a lot of "siteinfo". I suggest calling the struct `siteinfo.Client{}`. And, please use a different variable and package name.
</blockquote></details>

Done. Now it's `client` and I've moved it to the `switches()` func since the logic to extract switch hostnames from the `switches.json` siteinfo format has been moved here to keep the `siteinfo` package cleaner.
___
*[cmd/switch-monitoring/switch-monitoring, line  at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jO9UzCje-Y9tdbNOV:-M2nxGKfBlKQBs45XO6e:b-896fix) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/cmd/switch-monitoring/switch-monitoring#L)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This looks like a mistake? Please remove.
</blockquote></details>

Done.
___
*[cmd/switch-monitoring/client/netconf.go, line 1 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jNizm3H7CnOuCLkX6:-M3BiMl43fV5lHKCTNJ2:b-896fix) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/cmd/switch-monitoring/client/netconf.go#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest naming this package `netconf`. Then, usage would look like `netconf.Client` or `netconf.New`.
</blockquote></details>

Done.
___
*[cmd/switch-monitoring/client/netconf.go, line 54 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jPkYn4z7Nb1gAAMl2:-M3BiTewBOpC0MipKL5z:b-vy7wwi) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/cmd/switch-monitoring/client/netconf.go#L54)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Can we identify the default password hash? (eventually?)
</blockquote></details>

In the end we should be able to generate the encrypted password in genconfig.py, so the `.conf` we store in GCS is exactly the same as the one we get from the switch and we just need to check them for equality.
___
*[cmd/switch-monitoring/siteinfo/siteinfo.go, line 62 at r1](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2jQ5gSBFRSbGfvpg-g:-M3BjdOR68Q1f4alXvkZ:b3wg36o) ([raw file](https://github.com/m-lab/switch-monitoring/blob/a5dda6ff1a6fbe5cf71aacc7a7463be6f6939169/cmd/switch-monitoring/siteinfo/siteinfo.go#L62)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If this package will be part of a long-lived daemon, then I suggest using http requests with timeouts. This could be by using a custom `http.DefaultClient` (no timeouts) or using `http.NewRequestWithContext` with a context timeout.
</blockquote></details>

Done. Now the HTTP client is passed when constructing a `siteinfo.Client` and configured in `main.go` with a default of 15 seconds.
___
*[netconf/client.go, line 44 at r2](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M2niQ6V20uHRpa0HCdJ:-M2nxJOx2f6wlPGSm95e:b-iik7wo) ([raw file](https://github.com/m-lab/switch-monitoring/blob/aeb0780b177275422d0679411395da91cb9aca98/netconf/client.go#L44)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Is this only intended to remove the first comment line in the file, inserted dynamically by JunOS? 
</blockquote></details>

@nkinkade Yes. I would compare everything else line-by-line, including comments. I've noticed that manual changes to a section that contains a comment may delete the comment. The idea is that switch configs are driven by the templates in switch-config (plus genconfig.py, or its future replacement) and manual changes should always trigger some sort of warning. At the same time, re-applying the standard configuration should be trivial.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
This PR is getting pretty big. Looks like ~1000 lines of Go.

I've added a few comments. My general sense is that the unit tests could be a little simpler.

> Reviewed 3 of 8 files at r2, 6 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-:-M3CsUK7CTJpBZMXVo11:b-dnx7hb)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade, @robertodauria, and @stephen-soltesz)

___
*[.travis.yml, line 10 at r3](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M3CeagM9ullbx40AxZm:-M3CeagM9ullbx40AxZn:b-8wr29t) ([raw file](https://github.com/m-lab/switch-monitoring/blob/f0aa428ee0012f0a2552b077d57093c2eef3243b/.travis.yml#L10)):*
> ```YAML
> 
> script:
> - go test -covermode=count -coverprofile=profile.cov ./...
> ```

Please add:

```
- go vet ./...
- go test ./... -race
```

These are becoming the norm among new projects.
___
*[internal/siteinfo/client_test.go, line 24 at r3](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M3ClRuV4t-a8PRHeFLb:-M3ClRuV4t-a8PRHeFLc:bylag8q) ([raw file](https://github.com/m-lab/switch-monitoring/blob/f0aa428ee0012f0a2552b077d57093c2eef3243b/internal/siteinfo/client_test.go#L24)):*
> ```Go
> }
> 
> func (prov fileReaderProvider) Get(string) (*http.Response, error) {
> ```

Tests must be correct by inspection. There's a lot of machinery here. Can this be simpler?

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/switch-monitoring/1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[.travis.yml, line 10 at r3](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M3CeagM9ullbx40AxZm:-M3CwrXV1UR9C9E3zVRB:b-896fix) ([raw file](https://github.com/m-lab/switch-monitoring/blob/f0aa428ee0012f0a2552b077d57093c2eef3243b/.travis.yml#L10)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add:

```
- go vet ./...
- go test ./... -race
```

These are becoming the norm among new projects.
</blockquote></details>

Done.
___
*[internal/siteinfo/client_test.go, line 24 at r3](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M3ClRuV4t-a8PRHeFLb:-M3GZrZK5ejbNYHOr57w:bilb2ns) ([raw file](https://github.com/m-lab/switch-monitoring/blob/f0aa428ee0012f0a2552b077d57093c2eef3243b/internal/siteinfo/client_test.go#L24)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Tests must be correct by inspection. There's a lot of machinery here. Can this be simpler?
</blockquote></details>

What do you think of it now? I've removed all the conditionals by making different mock objects to test the various scenarios. Each mock object is (I believe) correct by inspection.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: - thank you for the test simplifications. maybe a general guideline for how to achieve simpler tests is that fewer branches in unit tests is better when possible by using literal, single-purpose objects.

> Reviewed 5 of 14 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-:-M3HF8p2EQEuExNTjujV:brptq0g)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[internal/siteinfo/client_test.go, line 24 at r3](https://reviewable.io/reviews/m-lab/switch-monitoring/1#-M3ClRuV4t-a8PRHeFLb:-M3HEmHvBGSy8HZZ8OmJ:b8eau52) ([raw file](https://github.com/m-lab/switch-monitoring/blob/f0aa428ee0012f0a2552b077d57093c2eef3243b/internal/siteinfo/client_test.go#L24)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

What do you think of it now? I've removed all the conditionals by making different mock objects to test the various scenarios. Each mock object is (I believe) correct by inspection. 
</blockquote></details>

I like it.

**Pull request merged**
